### ISSUE TITLE
Analog use gmdate

### ISSUE THREAD

**Issue by melbichon** [jbroadway/analog#14]
Gmdate() is used to print current date.
Why don't you use date() ?
Can you add a way to configure this ?

**Comment by lux** [comment]
This should be able to be solved via the `Analog::$timezone` setting now:

https://github.com/jbroadway/analog/blob/08ec5a01769fbebeb13df4900ecdd48914b1dc42/lib/Analog/Analog.php#L159

**Comment by lucasmichel** [comment]
I would like to suggest a new method in analog/lib/Analog/Analog.php :

public static function setTimeZone ($timezone) {
            self::$timezone = $timezone;
}

**Comment by jbroadway** [comment]
@lucasmichel I'm into that. Would you like to make a PR for it?

**Comment by lucasmichel** [comment]
> @lucasmichel I'm into that. Would you like to make a PR for it?

yes, as soon as i have some time here i do.
