### ISSUE TITLE
question: is it on purpose that the date is inserted as a string in MongoDB?

### ISSUE THREAD

**Issue by tessus** [jbroadway/analog#21]
I'm just wondering if it is on purpose that the date is inserted into a MongoDB collection as a string instead of a date field.

**Comment by jbroadway** [comment]
Just that the Mongo handler is fairly rudimentary. I'm open to improvements though! :)

**Comment by tessus** [comment]
Ok, I was just curious. But I did some digging and found out that the Mongo date field does not include a timezone.
Thus it probably makes sense for a logger to use a string instead.
(Otherwise I would have changed it and sent you a pull request.)
