### ISSUE TITLE
Null is reserved in PHP 7

### ISSUE THREAD

**Issue by remicollet** [jbroadway/analog#22]
PHP Fatal error:  Cannot use 'Null' as class name as it is reserved in xxx/Analog/Handler/Null.php on line 14

**Comment by remicollet** [comment]
Probably the trivial fix is to create a "Nothing" handlers and set the "Null" one as deprecated.

**Comment by jbroadway** [comment]
Thanks for the head's up. Just changed it in this commit:

https://github.com/jbroadway/analog/commit/e9edc16f45f4205246ae9ed0ce623910a7111dfd

Going to do a once-over to check for other mentions before closing this out.
