### ISSUE TITLE
Class Mail. Request best config

### ISSUE THREAD

**Issue by abkrim** [jbroadway/analog#23]
Hi.

On this days it's best way to send email trought authenticate SMTP )spam system, security)
It's possible add funcionality on nexts versions?

Apreciate you time.

**Comment by jbroadway** [comment]
For that I would probably add a handler that ties into one of the popular PHP mail packages (e.g., [SwiftMailer](http://swiftmailer.org/), [PHPMailer](https://github.com/PHPMailer/PHPMailer), or [Zend\Mail](http://framework.zend.com/manual/current/en/index.html#zend-mail)).

In the meantime, if you're looking for that functionality right now, take a look at the [Mail handler](https://github.com/jbroadway/analog/blob/master/lib/Analog/Handler/Mail.php) and you'll see it's very straightforward to create a custom handler based on that.

**Comment by abkrim** [comment]
A lot of thanks. Try to create custom handler.
