### ISSUE TITLE
Cannot use 'Null' as class name as it is reserved

### ISSUE THREAD

**Issue by michabbb** [jbroadway/analog#30]
https://github.com/jbroadway/analog/blob/08ec5a01769fbebeb13df4900ecdd48914b1dc42/lib/Analog/Handler/Null.php#L17

[phpstan](https://github.com/phpstan/phpstan) says: `Cannot use 'Null' as class name as it is reserved` - and i guess, it´s right 😏

**Comment by tessus** [comment]
yea, that's why the following is written right at the top. ;-)

https://github.com/jbroadway/analog/blob/08ec5a01769fbebeb13df4900ecdd48914b1dc42/lib/Analog/Handler/Null.php#L6-L7

**Comment by michabbb** [comment]
😄 didn´t see that 👍
