### ISSUE TITLE
Direct output

### ISSUE THREAD

**Issue by Nerahikada** [jbroadway/analog#37]
Is there a way to output logs directly (to the console, etc.)?

**Comment by Nerahikada** [comment]
Should I implement it or send a pull request?

**Comment by lux** [comment]
There isn't a specific handler for that (the closest is probably Stderr), but I imagine a simple "Echo" handler could do the trick. Something like this ought to work:

```php
namespace Analog\Handler;

class Echo {
	public static function init () {
		return function ($info) {
			vprintf (\Analog\Analog::$format, $info);
		};
	}
}
```

Happy to accept a PR for it too :)
