### ISSUE TITLE
Output converted log level

### ISSUE THREAD

**Issue by Nerahikada** [jbroadway/analog#38]
https://github.com/jbroadway/analog/blob/32ccdc89082a1cf9e471f4ce69f1c05bf741b34e/lib/Analog/Logger.php#L212

According to this comment, the logging level seems to be output after being converted, but the actual output is a number. Is this a bug?

**Comment by lux** [comment]
I think you're correct. The level should probably be converted to one of the strings in the PSR (https://www.php-fig.org/psr/psr-3/#5-psrlogloglevel).

**Comment by lux** [comment]
I forgot that there is a handler that converts log levels to their names, called LevelName. It acts as a filter and passes the log output along to whatever handler you tell it to from there.

Here's an example of its usage:

https://github.com/jbroadway/analog/blob/master/examples/levelname.php
