### ISSUE TITLE
how to use it without composer?

### ISSUE THREAD

**Issue by chenbimo** [jbroadway/analog#41]
i run my php in virtual machine and have't composer.

**Comment by lux** [comment]
If you clone this repository, you should be able to load it via:

```php
<?php

require 'analog/lib/Analog.php';

Analog::handler (Analog\Handler\Stderr::init ());

Analog::log ('Output to php://stderr');
```

It uses a simple autoloader internally, so you shouldn't need to include anything else. Hope that helps!

**Comment by lux** [comment]
If you clone this repository, you should be able to load it via:

```php
<?php

require 'analog/lib/Analog.php';

Analog::handler (Analog\Handler\Stderr::init ());

Analog::log ('Output to php://stderr');
```

It uses a simple autoloader internally, so you shouldn't need to include anything else. Hope that helps!

**Comment by lux** [comment]
If you clone this repository, you should be able to load it via:

```php
<?php

require 'analog/lib/Analog.php';

Analog::handler (Analog\Handler\Stderr::init ());

Analog::log ('Output to php://stderr');
```

It uses a simple autoloader internally, so you shouldn't need to include anything else. Hope that helps!

**Comment by lux** [comment]
Sorry if there were duplicate notifications there, GitHub is having issues atm :)

**Comment by chenbimo** [comment]
OK,very thinks!
