### ISSUE TITLE
Uncaught Error: Undefined class constant 'ATTR_ERRMODE' in  analog/analog/lib/Analog/Handler/PDO.php:52

### ISSUE THREAD

**Issue by v0ff4k** [jbroadway/analog#46]
Uncaught Error: Undefined class constant 'ATTR_ERRMODE' in ..../vendor/analog/analog/lib/Analog/Handler/PDO.php:52

Because your class  named PDO(as global) but your had no CONST NAMES!!!!! set **\PDO** const names instead **PDO** you forgot a slash sign, like:

```
class PDO {
	public static function init ($pdo, $table) {
		if (is_array ($pdo)) {
			$pdo = new \PDO ($pdo[0], $pdo[1], $pdo[2], [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION]);
		}
```

cause if i send $pdo as PDO object, it all works well, untill i send as array, and all executed as (without slash)

```
class PDO {
	public static function init ($pdo, $table) {
		if (is_array ($pdo)) {
			$pdo = new \PDO ($pdo[0], $pdo[1], $pdo[2], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
		}
```

**Comment by lux** [comment]
Just pushed a fix. Thanks for the head's up!
